routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::middleware(['auth:sanctum'])->group(function(){
    Route::resource('systems', 'App\Http\Controllers\SystemController');
    Route::get(
        'systems/{system}/destroyform',
        [
            'as' => 'systems.destroyform',
            'uses' => 'App\Http\Controllers\SystemController@destroyform'
        ]
    );
    Route::resource('users', 'App\Http\Controllers\UserController');
    Route::get(
        'users/{user}/destroyform',
        [
            'as' => 'users.destroyform',
            'uses' => 'App\Http\Controllers\UserController@destroyform'
        ]
    );
});

app/Models/User.php
<?php

namespace App\Models;

use App\Traits\FullSearch;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;
    use FullSearch;

    const PAGINATE_LIST = [5 => 5, 10 => 10, 25 => 25, 50 => 50, 100 => 100];
    const PAGINATE_DEFAULT = 10;

    const FILTERED = [
        'id'         => "N°",
        'name'       => "Name",
        'email'      => "Email",
        'superuser'  => "Admin",
        'created_at' => "Created",
        'updated_at' => "Updated",
    ];

    protected $fillname = ['name'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'superuser',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if (Auth::user()->superuser != 1) abort(404);

        $users = User::orderBy('id', 'DESC');

        // Search
        $search = $request->get('search');
        $option = $request->get('option');

        $users->filterSearchAll($search, User::FILTERED);

        // Paginate
        $paginate = $request->get('paginate') ?? User::PAGINATE_DEFAULT;

        $users = $users->paginate($paginate);

        return view('users.index', compact('users', 'search', 'paginate', 'option'));
        // users/index.blade.php
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        if (Auth::user()->superuser != 1) abort(404);

        return view('users.show', compact('user'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroyform(User $user)
    {
        if (Auth::user()->superuser != 1) abort(404);

        return view('users.destroyform', compact('user'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        if (Auth::user()->superuser != 1) abort(404);

        $user->delete();
        return redirect(route('users.index'))->with([
            'message' => 'The user was deleted correctly',
            'type' => 'danger',
        ]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/users/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Dashboard
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="row">
                <div class="col-12">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ url('/') }}">Inicio</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('users.index') }}">Users</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Create User</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul class="mb-0">
                            @foreach ($errors->all() as $error)
                            <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                    <br />
                    @endif
                    <form method="post" action="{{route('users.store')}}">
                        @csrf
                        <div class="card">
                            <h5 class="card-header bg-success text-white">
                                <i class="fa fa-id-badge"></i>
                                Create User
                            </h5>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                        <div class="form-group">
                                            <label for="name">Name:</label>
                                            <input type="text" class="form-control" name="name" value="{{old('name')}}" placeholder="Name" />
                                        </div>
                                    </div>
                                    <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                        <div class="form-group">
                                            <label for="email">Email:</label>
                                            <input type="text" class="form-control" name="email" value="{{old('email')}}" placeholder="Email" />
                                        </div>
                                    </div>
                                    <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                        <div class="form-group">
                                            <label for="superuser">Admin:</label>
                                            {{ Form::select('superuser', [1 => 'Yes', null => 'No'], old('superuser'), ['class' => 'form-control']) }}
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-9">
                                        <div class="form-group">
                                            <label for="publickey">Public Key:</label>
                                            <textarea class="form-control" name="publickey" placeholder="Public Key" style="height: 200px;">{{old('publickey')}}</textarea>
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-sm btn-success">
                                    Guardar
                                </button>
                                <a href="{{route('users.index')}}" class="btn btn-sm btn-link">
                                    Cancelar
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/users/destroyform.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Dashboard
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="row">
                <div class="col-12">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ url('/') }}">Inicio</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('users.index') }}">Users</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Delete User</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul class="mb-0">
                            @foreach ($errors->all() as $error)
                            <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                    <br />
                    @endif
                    <form method="post" action="{{route('users.destroy', $user->id)}}">
                        @csrf
                        @method('DELETE')
                        <div class="col-12">
                            <div class="card">
                                <h5 class="card-header bg-danger text-white">
                                    <i class="fa fa-id-badge"></i>
                                    Delete User
                                </h5>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                            <div class="form-group">
                                                <label>Name:</label>
                                                <input disabled type="text" class="form-control" value="{{ $user->name }}" />
                                            </div>
                                        </div>
                                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                            <div class="form-group">
                                                <label>Email:</label>
                                                <input disabled type="text" class="form-control" value="{{ $user->email }}" />
                                            </div>
                                        </div>
                                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                            <div class="form-group">
                                                <label>Admin:</label>
                                                <input disabled type="text" class="form-control" value="{{ $user->superuser ? 'Yes' : 'No' }}" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                            <div class="form-group">
                                                <label>Created:</label>
                                                <input disabled type="text" class="form-control" value="{{ \Carbon\Carbon::parse($user->created_at)->format('d/m/Y H:i:s') }}" />
                                            </div>
                                        </div>
                                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                            <div class="form-group">
                                                <label>Updated:</label>
                                                <input disabled type="text" class="form-control" value="{{ \Carbon\Carbon::parse($user->updated_at)->format('d/m/Y H:i:s') }}" />
                                            </div>
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-sm btn-danger">
                                        Delete
                                    </button>
                                    <a href="{{route('users.index')}}" class="btn btn-sm btn-link">
                                        Cancelar
                                    </a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/users/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Dashboard
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="row">
                <div class="col-12">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ url('/') }}">Inicio</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('users.index') }}">Lista de User</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Edit User</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul class="mb-0">
                            @foreach ($errors->all() as $error)
                            <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                    <br />
                    @endif
                    <form method="post" action="{{route('users.update', $user->id)}}">
                        @csrf
                        @method('PATCH')
                        <div class="col-12">
                            <div class="card">
                                <h5 class="card-header bg-primary text-white">
                                    <i class="fa fa-id-badge"></i>
                                    Edit User
                                </h5>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                            <div class="form-group">
                                                <label for="name">Name:</label>
                                                <input type="text" class="form-control" name="name" value="{{old('name', $user->name)}}" />
                                            </div>
                                        </div>
                                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                            <div class="form-group">
                                                <label for="name">Domain:</label>
                                                <input type="text" class="form-control" name="domain" value="{{old('domain', $user->domain)}}" />
                                            </div>
                                        </div>
                                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                            <div class="form-group">
                                                <label for="name">Hash:</label>
                                                <input type="text" class="form-control" name="hash" value="{{old('hash', $user->hash)}}" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-9">
                                            <div class="form-group">
                                                <label for="name">Public Key:</label>
                                                <textarea class="form-control" name="publickey" style="height: 200px;">{{old('publickey', $user->publickey)}}</textarea>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                            <div class="form-group">
                                                <label>Created:</label>
                                                <input disabled type="text" class="form-control" value="{{ \Carbon\Carbon::parse($user->created_at)->format('d/m/Y H:i:s') }}" />
                                            </div>
                                        </div>
                                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                            <div class="form-group">
                                                <label>Updated:</label>
                                                <input disabled type="text" class="form-control" value="{{ \Carbon\Carbon::parse($user->updated_at)->format('d/m/Y H:i:s') }}" />
                                            </div>
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-sm btn-primary">
                                        Guardar
                                    </button>
                                    <a href="{{route('users.index')}}" class="btn btn-sm btn-link">
                                        Cancelar
                                    </a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/users/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Dashboard
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div class="row">
                    <div class="col-12">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{ url('/') }}">Inicio</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Users</li>
                            </ol>
                        </nav>
                    </div>
                </div>
                <div class="row">
                    @if(session()->get('message'))
                        <div class="col-12">
                            <div class="alert alert-{{ session()->get('type') ?? 'message' }}">{{session()->get('message')}}</div>
                        </div>
                    @endif
                    <div class="col-12">
                        <div class="card">
                            <h5 class="card-header bg-dark text-white">
                                <i class="fa fa-id-badge"></i>
                                Users
                            </h5>
                            <div class="card-body">
                                <div class="col-12">
                                    {{ $users->links() }}
                                </div>
                                <div class="col-12">
                                    <div class="table-responsive">
                                        {{ Form::open(['url' => route('users.index'), 'method' => 'get', 'id' => 'grid_filter_form']) }}
                                            <table class="table table-striped">
                                                <thead>
                                                    <tr>
                                                        @foreach (App\Models\User::FILTERED as $key => $value)
                                                            <td>
                                                                <input
                                                                    @if (substr($key, -3, 3) == '_at')
                                                                        type="date"
                                                                        class="form-control form-control-sm datepicker"
                                                                    @else
                                                                        type="text"
                                                                        class="form-control form-control-sm"
                                                                    @endif
                                                                    name="search[{{ $key }}]"
                                                                    value="{{ isset($search[$key]) ? $search[$key] : '' }}"
                                                                    placeholder="{{ $value }}"
                                                                >
                                                            </td>
                                                        @endforeach
                                                        <td>
                                                            <button type="submit" class="btn btn-sm btn-success">Buscar</button>
                                                            <a href="{{ route('users.index') }}" class="btn btn-sm btn-secondary">
                                                                Limpiar
                                                            </a>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <th>N°</th>
                                                        <th>Name</th>
                                                        <th>Email</th>
                                                        <th>Admin</th>
                                                        <th>Created</th>
                                                        <th>Updated</th>
                                                        <th></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @if (count($users))
                                                        @foreach ($users as $user)
                                                            <tr>
                                                                <th scope="row">{{ $user->id }}</th>
                                                                <td>{{ $user->name }}</td>
                                                                <td>{{ $user->email }}</td>
                                                                <td>{{ $user->superuser == '1' ? 'Yes' : 'No' }}</td>
                                                                <td>{{ \Carbon\Carbon::parse($user->created_at) ? Carbon\Carbon::parse(\Carbon\Carbon::parse($user->created_at))->format('d/m/Y H:i').'hs' : ''}}</td>
                                                                <td>{{ \Carbon\Carbon::parse($user->updated_at) ? Carbon\Carbon::parse(\Carbon\Carbon::parse($user->updated_at))->format('d/m/Y H:i').'hs' : ''}}</td>
                                                                <td style="white-space: nowrap;">
                                                                    <a href="{{ route('users.show', $user->id) }}" class="btn btn-sm btn-secondary"><i class="fa fa-eye"></i> Show</a>
                                                                    @if ($user->superuser != 1)
                                                                        <a href="{{ route('users.destroyform', $user->id) }}" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> Logout</a>
                                                                    @else
                                                                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                                    @endif
                                                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                                </td>
                                                            </tr>
                                                        @endforeach
                                                    @else
                                                        <tr>
                                                            <td colspan="100%">
                                                                Users not found
                                                            </td>
                                                        </tr>
                                                    @endif
                                                </tbody>
                                                <tfoot>
                                                    <tr>
                                                        <th colspan="100%">
                                                            {{ $users->total() }} Items.
                                                        </th>
                                                    </tr>
                                                </tfoot>
                                            </table>
                                        {{ Form::close() }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>