routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::middleware(['auth:sanctum'])->group(function(){
    Route::resource('systems', 'App\Http\Controllers\SystemController');
    Route::get(
        'systems/{system}/destroyform',
        [
            'as' => 'systems.destroyform',
            'uses' => 'App\Http\Controllers\SystemController@destroyform'
        ]
    );
    Route::resource('users', 'App\Http\Controllers\UserController');
    Route::get(
        'users/{user}/destroyform',
        [
            'as' => 'users.destroyform',
            'uses' => 'App\Http\Controllers\UserController@destroyform'
        ]
    );
});

app/Models/System.php
<?php

namespace App\Models;

use App\Traits\FullSearch;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class System extends Model
{
    use HasFactory;
    use FullSearch;

    const PAGINATE_LIST = [5 => 5, 10 => 10, 25 => 25, 50 => 50, 100 => 100];
    const PAGINATE_DEFAULT = 10;

    const FILTERED = [
        'id'         => "N°",
        'name'       => "Name",
        'domain'     => "Domain",
        'hash'       => "Hash",
        'created_at' => "Created",
        'updated_at' => "Updated",
    ];

    protected $fillname = ['name'];

    protected $fillable = [
        'name',
        'domain',
        'hash',
        'publickey',
    ];
}

app/Http/Controllers/SystemController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreSystemRequest;
use App\Http\Requests\UpdateSystemRequest;
use App\Models\System;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class SystemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if (Auth::user()->superuser != 1) abort(404);

        $systems = System::orderBy('id', 'DESC');

        // Search
        $search = $request->get('search');
        $option = $request->get('option');

        $systems->filterSearchAll($search, System::FILTERED);

        // Paginate
        $paginate = $request->get('paginate') ?? System::PAGINATE_DEFAULT;

        $systems = $systems->paginate($paginate);

        return view('systems.index', compact('systems', 'search', 'paginate', 'option'));
        // systems/index.blade.php
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->superuser != 1) abort(404);

        return view('systems.create');
        // systems/create.blade.php
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreSystemRequest $request)
    {
        if (Auth::user()->superuser != 1) abort(404);

        $system = new System($request->validated());
        $system->save();
        return redirect(route('systems.index'))->with([
            'message' => 'The system was added correctly',
            'type' => 'success',
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\System  $system
     * @return \Illuminate\Http\Response
     */
    public function show(System $system)
    {
        if (Auth::user()->superuser != 1) abort(404);

        return view('systems.show', compact('system'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\System  $system
     * @return \Illuminate\Http\Response
     */
    public function edit(System $system)
    {
        if (Auth::user()->superuser != 1) abort(404);

        return view('systems.edit', compact('system'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\System  $system
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateSystemRequest $request, System $system)
    {
        if (Auth::user()->superuser != 1) abort(404);

        $system->update($request->validated());
        return redirect(route('systems.index'))->with([
            'message' => 'The system was changed correctly',
            'type' => 'primary',
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\System  $system
     * @return \Illuminate\Http\Response
     */
    public function destroyform(System $system)
    {
        if (Auth::user()->superuser != 1) abort(404);

        return view('systems.destroyform', compact('system'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\System  $system
     * @return \Illuminate\Http\Response
     */
    public function destroy(System $system)
    {
        if (Auth::user()->superuser != 1) abort(404);

        $system->delete();
        return redirect(route('systems.index'))->with([
            'message' => 'The system was deleted correctly',
            'type' => 'danger',
        ]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/systems/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Dashboard
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="row">
                <div class="col-12">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ url('/') }}">Inicio</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('systems.index') }}">Systems</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Create System</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul class="mb-0">
                            @foreach ($errors->all() as $error)
                            <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                    <br />
                    @endif
                    <form method="post" action="{{route('systems.store')}}">
                        @csrf
                        <div class="card">
                            <h5 class="card-header bg-success text-white">
                                <i class="fa fa-id-badge"></i>
                                Create System
                            </h5>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                        <div class="form-group">
                                            <label for="name">Name:</label>
                                            <input type="text" class="form-control" name="name" value="{{old('name')}}" placeholder="Name" />
                                        </div>
                                    </div>
                                    <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                        <div class="form-group">
                                            <label for="domain">Domain:</label>
                                            <input type="text" class="form-control" name="domain" value="{{old('domain')}}" placeholder="Domain" />
                                        </div>
                                    </div>
                                    <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                        <div class="form-group">
                                            <label for="hash">Hash:</label>
                                            <input type="text" class="form-control" name="hash" value="{{old('hash')}}" placeholder="Hash" />
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-9">
                                        <div class="form-group">
                                            <label for="publickey">Public Key:</label>
                                            <textarea class="form-control" name="publickey" placeholder="Public Key" style="height: 200px;">{{old('publickey')}}</textarea>
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-sm btn-success">
                                    Guardar
                                </button>
                                <a href="{{route('systems.index')}}" class="btn btn-sm btn-link">
                                    Cancelar
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/systems/destroyform.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Dashboard
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="row">
                <div class="col-12">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ url('/') }}">Inicio</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('systems.index') }}">Systems</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Delete System</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul class="mb-0">
                            @foreach ($errors->all() as $error)
                            <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                    <br />
                    @endif
                    <form method="post" action="{{route('systems.destroy', $system->id)}}">
                        @csrf
                        @method('DELETE')
                        <div class="col-12">
                            <div class="card">
                                <h5 class="card-header bg-danger text-white">
                                    <i class="fa fa-id-badge"></i>
                                    Delete System
                                </h5>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                            <div class="form-group">
                                                <label>Name:</label>
                                                <input disabled type="text" class="form-control" value="{{ $system->name }}" />
                                            </div>
                                        </div>
                                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                            <div class="form-group">
                                                <label>Domain:</label>
                                                <input disabled type="text" class="form-control" value="{{ $system->domain }}" />
                                            </div>
                                        </div>
                                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                            <div class="form-group">
                                                <label>Hash:</label>
                                                <input disabled type="text" class="form-control" value="{{ $system->hash }}" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-9">
                                            <div class="form-group">
                                                <label>Public Key:</label>
                                                <textarea disabled class="form-control" style="height: 200px;">{{ $system->publickey }}</textarea>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                            <div class="form-group">
                                                <label>Created:</label>
                                                <input disabled type="text" class="form-control" value="{{ \Carbon\Carbon::parse($system->created_at)->format('d/m/Y H:i:s') }}" />
                                            </div>
                                        </div>
                                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                            <div class="form-group">
                                                <label>Updated:</label>
                                                <input disabled type="text" class="form-control" value="{{ \Carbon\Carbon::parse($system->updated_at)->format('d/m/Y H:i:s') }}" />
                                            </div>
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-sm btn-danger">
                                        Delete
                                    </button>
                                    <a href="{{route('systems.index')}}" class="btn btn-sm btn-link">
                                        Cancelar
                                    </a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/systems/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Dashboard
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="row">
                <div class="col-12">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ url('/') }}">Inicio</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('systems.index') }}">Lista de System</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Edit System</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul class="mb-0">
                            @foreach ($errors->all() as $error)
                            <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                    <br />
                    @endif
                    <form method="post" action="{{route('systems.update', $system->id)}}">
                        @csrf
                        @method('PATCH')
                        <div class="col-12">
                            <div class="card">
                                <h5 class="card-header bg-primary text-white">
                                    <i class="fa fa-id-badge"></i>
                                    Edit System
                                </h5>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                            <div class="form-group">
                                                <label for="name">Name:</label>
                                                <input type="text" class="form-control" name="name" value="{{old('name', $system->name)}}" />
                                            </div>
                                        </div>
                                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                            <div class="form-group">
                                                <label for="name">Domain:</label>
                                                <input type="text" class="form-control" name="domain" value="{{old('domain', $system->domain)}}" />
                                            </div>
                                        </div>
                                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                            <div class="form-group">
                                                <label for="name">Hash:</label>
                                                <input type="text" class="form-control" name="hash" value="{{old('hash', $system->hash)}}" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-9">
                                            <div class="form-group">
                                                <label for="name">Public Key:</label>
                                                <textarea class="form-control" name="publickey" style="height: 200px;">{{old('publickey', $system->publickey)}}</textarea>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                            <div class="form-group">
                                                <label>Created:</label>
                                                <input disabled type="text" class="form-control" value="{{ \Carbon\Carbon::parse($system->created_at)->format('d/m/Y H:i:s') }}" />
                                            </div>
                                        </div>
                                        <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                                            <div class="form-group">
                                                <label>Updated:</label>
                                                <input disabled type="text" class="form-control" value="{{ \Carbon\Carbon::parse($system->updated_at)->format('d/m/Y H:i:s') }}" />
                                            </div>
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-sm btn-primary">
                                        Guardar
                                    </button>
                                    <a href="{{route('systems.index')}}" class="btn btn-sm btn-link">
                                        Cancelar
                                    </a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/systems/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Dashboard
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div class="row">
                    <div class="col-12">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{ url('/') }}">Inicio</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Systems</li>
                            </ol>
                        </nav>
                    </div>
                </div>
                <div class="row">
                    @if(session()->get('message'))
                        <div class="col-12">
                            <div class="alert alert-{{ session()->get('type') ?? 'message' }}">{{session()->get('message')}}</div>
                        </div>
                    @endif
                    <div class="col-12">
                        <div class="card">
                            <h5 class="card-header bg-dark text-white">
                                <i class="fa fa-id-badge"></i>
                                Systems
                            </h5>
                            <div class="card-body">
                                <div class="col-12">
                                    {{ $systems->links() }}
                                </div>
                                <div class="col-12">
                                    <div class="table-responsive">
                                        {{ Form::open(['url' => route('systems.index'), 'method' => 'get', 'id' => 'grid_filter_form']) }}
                                            <table class="table table-striped">
                                                <thead>
                                                    <tr>
                                                        @foreach (App\Models\System::FILTERED as $key => $value)
                                                            <td>
                                                                <input
                                                                    @if (substr($key, -3, 3) == '_at')
                                                                        type="date"
                                                                        class="form-control form-control-sm datepicker"
                                                                    @else
                                                                        type="text"
                                                                        class="form-control form-control-sm"
                                                                    @endif
                                                                    name="search[{{ $key }}]"
                                                                    value="{{ isset($search[$key]) ? $search[$key] : '' }}"
                                                                    placeholder="{{ $value }}"
                                                                >
                                                            </td>
                                                        @endforeach
                                                        <td>
                                                            <button type="submit" class="btn btn-sm btn-success">Buscar</button>
                                                            <a href="{{ route('systems.index') }}" class="btn btn-sm btn-secondary">
                                                                Limpiar
                                                            </a>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <th>N°</th>
                                                        <th>Name</th>
                                                        <th>Domain</th>
                                                        <th>Hash</th>
                                                        <th>Created</th>
                                                        <th>Updated</th>
                                                        <th>
                                                            <a href="{{ route('systems.create') }}" class="btn btn-sm btn-success"><i class="fa fa-plus"></i> Create</a>
                                                        </th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @if (count($systems))
                                                        @foreach ($systems as $system)
                                                            <tr>
                                                                <th scope="row">{{ $system->id }}</th>
                                                                <td>{{ $system->name }}</td>
                                                                <td>{{ $system->domain }}</td>
                                                                <td>{{ $system->hash }}</td>
                                                                <td>{{ \Carbon\Carbon::parse($system->created_at) ? Carbon\Carbon::parse(\Carbon\Carbon::parse($system->created_at))->format('d/m/Y H:i').'hs' : ''}}</td>
                                                                <td>{{ \Carbon\Carbon::parse($system->updated_at) ? Carbon\Carbon::parse(\Carbon\Carbon::parse($system->updated_at))->format('d/m/Y H:i').'hs' : ''}}</td>
                                                                <td style="white-space: nowrap;">
                                                                    <a href="{{ route('systems.show', $system->id) }}" class="btn btn-sm btn-secondary"><i class="fa fa-eye"></i> Show</a>
                                                                    <a href="{{ route('systems.edit', $system->id) }}" class="btn btn-sm btn-primary"><i class="fa fa-edit"></i> Edit</a>
                                                                    <a href="{{ route('systems.destroyform', $system->id) }}" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> Delete</a>
                                                                </td>
                                                            </tr>
                                                        @endforeach
                                                    @else
                                                        <tr>
                                                            <td colspan="100%">
                                                                Systems not found
                                                            </td>
                                                        </tr>
                                                    @endif
                                                </tbody>
                                                <tfoot>
                                                    <tr>
                                                        <th colspan="100%">
                                                            {{ $systems->total() }} Items.
                                                        </th>
                                                    </tr>
                                                </tfoot>
                                            </table>
                                        {{ Form::close() }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>